---
- hosts: all
  become: True
  vars_files:
    - vars.yml
  tasks:
    - name: install Katello CA
      package:
        name: "http://{{ foreman_server }}/pub/katello-ca-consumer-latest.noarch.rpm"

    - name: subscribe to Katello
      redhat_subscription:
        org_id: "{{ organization | theforeman.foreman.cp_label }}"
        activationkey: "{{ activation_keys[0].name }}"

    - name: add SSH key
      authorized_key:
        user: root
        key: "https://{{ foreman_server }}:9090/ssh/pubkey"
