---
- hosts: all
  become: True
  roles:
    - role: epel_repositories
    - role: puppet_repositories
    - role: foreman_repositories
      vars:
        foreman_repositories_version: '2.3'
    - role: katello_repositories
      vars:
        katello_repositories_version: '3.18'

- hosts: all
  become: True
  pre_tasks:
    - name: install katello package
      package:
        name: katello
        state: present
  roles:
    - role: theforeman.operations.installer
      vars:
        installer_scenario: katello
        installer_options:
          - '--foreman-initial-admin-password changeme'
