---
- hosts: all
  become: True
  vars_files:
    - vars.yml
  roles:
    - role: epel_repositories
    - role: puppet_repositories
    - role: foreman_repositories
    - role: katello_repositories

- hosts: all
  become: True
  vars_files:
    - vars.yml
  pre_tasks:
    - name: install katello package
      package:
        name: katello
        state: present
  roles:
    - role: theforeman.operations.installer

- hosts: all
  vars_files:
    - vars.yml
  roles:
    - role: theforeman.foreman.repositories
  tasks:
    - name: "Sync repositories"
      theforeman.foreman.repository_sync:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        validate_certs: "{{ validate_certs }}"
        organization: "{{ organization }}"
        product: "{{ item.name }}"
      loop: "{{ products }}"

    - name: "Create Content Views"
      theforeman.foreman.content_view:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        validate_certs: "{{ validate_certs }}"
        organization: "{{ organization }}"
        name: "{{ item.name }}"
        repositories: "{{ item.repositories }}"
      loop: "{{ content_views }}"

    - name: "Create Composite Content Views"
      theforeman.foreman.content_view:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        validate_certs: "{{ validate_certs }}"
        organization: "{{ organization }}"
        name: "{{ item.name }}"
        components: "{{ item.components }}"
        composite: true
        auto_publish: true
      loop: "{{ composite_content_views }}"

    - name: "Initiall Publish of Content Views"
      theforeman.foreman.content_view_version:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        validate_certs: "{{ validate_certs }}"
        organization: "{{ organization }}"
        content_view: "{{ item.name }}"
        version: "1.0"
      loop: "{{ content_views }}"

- hosts: all
  vars_files:
    - vars.yml
  roles:
    - role: theforeman.foreman.activation_keys
